//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by VideoPreview.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_POPUP_EDIT                  119
#define IDR_POPUP_MENU                  119
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define ID_TOOLBAR_MAIN                 129
#define IDR_VideoPreviewTYPE            130
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDB_EXPLORER_24                 170
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_MENU_IMAGES_24              180
#define IDR_PROPERTIES                  183
#define ID_TOOLBAR_SETTINGS             183
#define IDB_NAVIGATION_LARGE            186
#define IDB_NAVIGATION_LARGE_HC         187
#define IDB_PAGES                       188
#define IDB_PAGES_HC                    189
#define IDB_PAGES_SMALL                 190
#define IDB_PAGES_SMALL_HC              191
#define ID_VIEW_CAPTION_BAR             221
#define IDB_INFO                        230
#define IDS_CAPTION_BUTTON              231
#define IDS_CAPTION_BUTTON_TIP          232
#define IDS_CAPTION_TEXT                233
#define IDS_CAPTION_IMAGE_TIP           234
#define IDS_CAPTION_IMAGE_TEXT          235
#define IDS_MYCALENDARS                 250
#define IDS_CALENDAR                    251
#define IDS_SHORTCUTS                   252
#define IDS_FOLDERS                     253
#define IDS_OUTLOOKBAR                  258
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDD_CHANGE_OUTPUT_PROFILE_NAME  308
#define IDD_OUTPUT_PROFILE              308
#define IDC_EDIT_OUTPUT_PROFILE_NAME    309
#define IDC_CBTN_COPY_FROM_OUTPUT_PROFILE 310
#define IDC_COMBO_OUTPUT_PROFILES       311
#define IDC_EDIT_OUTPUT_LOCATION        313
#define IDC_BTN_OUTPUT_DIRECTORY        314
#define IDC_RBTN_ACTION_ON_ERROR_SKIP   315
#define IDC_RBTN_ACTION_ON_ERROR_STOP   316
#define IDC_RBTN_ACTION_ON_ERROR_PROMT  317
#define IDC_CBTN_SAVE_FILE_LIST         318
#define IDC_LIST_SOURCE_FILE_TYPES      319
#define IDC_BTN_ADD_SOURCE_FILE_TYPE    320
#define IDC_EDIT_SOURCE_FILE_TYPE       321
#define IDC_BTN_REMOVE_SOURCE_FILE_TYPE 322
#define IDC_CBTN_USE_EXPLORER_CONTEXT_MENU 323
#define IDA_FILE_LIST                   323
#define IDC_CBTN_USE_SOURCE_FILE_LOCATION 324
#define IDC_CBTN_OVERWRITE_OUTPUT_FILES 325
#define IDC_BTN_DEFAULT_SOURCE_FILE_TYPE 326
#define IDD_SETTINGS                    329
#define ID_SETTINGS_PANE                330
#define IDC_STATIC_VERSION              1000
#define IDC_STATIC_APP_URL              1001
#define ID_CMD_TEST                     32771
#define ID_CMD_ADD_FILES                32774
#define ID_CMD_ADD_FOLDER               32775
#define ID_CMD_PROCESS_ALL              32776
#define ID_CMD_STOP_PROCESSING          32777
#define ID_FILE_REMOVECOMPLETED         32778
#define ID_FILE_REMOPEALL               32779
#define ID_CMD_OPTIONS                  32780
#define ID_FILE_REMOVEALL               32785
#define ID_CMD_PROFILE_SAVE             32788
#define ID_CMD_PROFILE_PREVIEW          32789
#define ID_CMD_PROFILE_DELETE           32792
#define ID_PROFILE_COMBO                32793
#define ID_PROFILE_DELETE32794          32794
#define ID_REMOVE_COMPLETED             32801
#define ID_CMD_REMOVE_ALL               32802
#define ID_CMD_REMOVE_COMPLETED         32803
#define ID_CMD_REMOVE_FAILED            32804
#define ID_EDIT_OPENVIDEO               32805
#define ID_EDIT_RESET                   32806
#define ID_FILE_OPENVIDEO               32808
#define ID_FILE_OPEN_VIDEO              32809
#define ID_FILE_OPEN_PREVIEW            32810
#define ID_FILE_PROCESS                 32811
#define ID_FILE_PROCESS_ITEM            32812
#define ID_FILE_RESET_ITEM              32813
#define ID_FILE_REMOVE_ITEM             32814
#define ID_CMD_REMOVE_SELECTED          32815
#define ID_CMD_RESET_SELECTED           32816
#define ID_CMD_PROCESS_SELECTED         32817
#define ID_CMD_OPEN_PREVIEW             32818
#define ID_CMD_OPEN_VIDEO               32819
#define ID_ROOT_BROWSETOVIDEO           32820
#define ID_CMD_BROWSETOVIDEO            32821
#define ID_ROOT_BROWSETOPREVIEW         32822
#define ID_CMD_BROWSETOPREVIEW          32823
#define ID_ROOT_REMOVECOMPLETED         32824
#define ID_ROOT_REMOVEFAILED            32825
#define ID_ROOT_REMOVEALL               32826
#define ID_ROOT_RESETALL                32827
#define ID_ROOT_PROCESSALL              32828
#define ID_CMD_BROWSE_TO_VIDEO          32829
#define ID_CMD_BROWSE_TO_PREVIEW        32830
#define ID_ROOT_RESET_ALL               32831
#define ID_CMD_RESET_ALL                32832
#define ID_HELP_GITHUB                  32833
#define ID_CMD_GITHUB                   32834
#define ID_CMD_ABOUT                    32835
#define ID_FILE_ADDFILES                32836
#define ID_ROOT_ADDFOLDER               32837
#define ID_CMD_ADD_PROFILE              32839
#define ID_BUTTON32842                  32842
#define ID_CMD_PROFILE_ADD              32842
#define ID_PROFILE_ADD                  32844
#define ID_COMBO_OUTPUT_DIR             32848
#define ID_CMD_SELECT_OUTPUT_DIR        32849
#define ID_CMD_SELECT_ALL_FILES         32855
#define ID_ROOT_REMOVE_ALL              32857
#define ID_CMD_PASTE_FILES              32858

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        324
#define _APS_NEXT_COMMAND_VALUE         32860
#define _APS_NEXT_CONTROL_VALUE         1002
#define _APS_NEXT_SYMED_VALUE           331
#endif
#endif
